# Generated by Django 6.0.2 on 2026-02-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='Choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='Question_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
